### ISSUE TITLE
user-waitinglist page: semua antrian milik user terkait

### ISSUE THREAD

**Issue by tesu-tesu** [tesu-tesu/antrian-sehat-backend#50]

**Comment by rochimatus** [comment]
(yg lagi diperiksa/nomer terakhir, nomer user, nama puskesmas & poli)

**Comment by tesu-tesu** [comment]
![image](https://user-images.githubusercontent.com/72516106/96366298-0b178700-1171-11eb-9cb1-3bd98dd5c007.png)
